import { createContext, useContext, useState, type ReactNode } from "react";

export type LangKey = "lo" | "th" | "en";

const LANG_STORAGE_KEY = "app_lang";

export const translations = {
  lo: {
    welcome: {
      skip: "ຂ້າມ",
      titleLine1: "ຍິນດີຕ້ອນຮັບສູ່",
      titleAccent: "ຊ່າງດ່ວນ",
      subtitle: "ຄົ້ນຫາຊ່າງໃກ້ບ້ານທ່ານໄດ້ໄວ ປອດໄພ ແລະ ເຊື່ອຖືໄດ້",
      start: "ເລີ່ມຕົ້ນ",
      checking: "ກຳລັງກວດສອບ...",
    },
    nav: {
      home: "ໜ້າຫຼັກ",
      bookings: "ແຊັດ",
      history: "ປະຫວັດ",
      profile: "ໂປຣໄຟລ໌",
    },
    home: {
      title: "ຊ່າງດ່ວນ",
      searchPlaceholder: "ຄົ້ນຫາຊື່ ຫຼື ພື້ນທີ່...",
      location: "ນະຄອນຫຼວງວຽງຈັນ",
      greet: (name: string) => `ສະບາຍດີ, ${name}`,
      banner: {
        badge: "ບໍລິການປອດໄພ",
        title: "ບໍລິການຊ່າງດ່ວນ",
        desc: "ຊ່າງເຂົ້າເຮືອນທ່ານ ວ່ອງໄວ ໄວ້ໃຈໄດ້ ພ້ອມສ່ວນຫຼຸດພິເສດ",
        discount: "ສ່ວນຫຼຸດ: 10%",
      },
      perksTitle: "ສິດທິພິເສດສຳລັບທ່ານ",
      perk1Title: "ສ່ວນຫຼຸດ 10%",
      perk1Desc: "ບໍລິການຊ່າງໄຟຟ້າຄັ້ງທຳອິດ",
      perk2Title: "ສ່ວນຫຼຸດ 5%",
      perk2Desc: "ບໍລິການທຸກປະເພດວັນທຳອິດ",
      categoriesTitle: "ໝວດໝູ່ບໍລິການ",
      featuredTitle: "ບໍລິການແນະນຳ",
      categories: {
        electric: "ຊ່າງໄຟຟ້າ",
        plumbing: "ຊ່າງນ້ຳປະປາ",
        beauty: "ຊ່າງເສີມສວຍ",
        carRepair: "ຊ່າງສ້ອມແປງລົດ",
        phoneRepair: "ຊ່າງສ້ອມແປງໂທລະສັບ",
        airRepair: "ຊ່າແອ",
      },
    },
    history: {
      title: "ປະຫວັດການໃຊ້ບໍລິການ",
      empty: "ຍັງບໍ່ມີປະຫວັດ",
      emptyDesc: "ປະຫວັດການໃຊ້ບໍລິການຂອງທ່ານຈະສະແດງຢູ່ນີ້",
      done: "ສຳເລັດ",
      cancelled: "ຍົກເລີກ",
    },
    bookings: {
      title: "ແຊັດ",
      loading: "ກຳລັງໂຫລດ...",
      empty: "ຍັງບໍ່ມີການແຊັດ",
      emptyDesc: "ເລີ່ມແຊັດຫາຊ່າງທີ່ໜ້າຫຼັກໄດ້ເລີຍ",
      startConvo: "ເລີ່ມການສົນທະນາ...",
      unread: "ຍັງບໍ່ອ່ານ",
    },
    technicianHome: {
      chatListTitle: (name: string) => `ລາຍການແຊັດ (${name})`,
      profileTitle: "ຂໍ້ມູນຊ່າງ",
      loading: "ກຳລັງໂຫລດ...",
      noTech: "ບໍ່ພົບຂໍ້ມູນຊ່າງ",
      noChats: "ຍັງບໍ່ມີລູກຄ້າແຊັດເຂົ້າມາ",
      tabChat: "ແຊັດລູກຄ້າ",
      tabProfile: "ຂໍ້ມູນຊ່າງ",
      logoutTitle: "ອອກຈາກລະບົບ",
      logoutConfirm: "ທ່ານແນ່ໃຈບໍ່ວ່າຈະອອກຈາກລະບົບ?",
      cancel: "ຍົກເລີກ",
      logout: "ອອກຈາກລະບົບ",
      unread: "ຍັງບໍ່ອ່ານ",
    },
    profile: {
      appTitle: "ຊ່າງດ່ວນ",
      loading: "ກຳລັງໂຫລດ...",
      newUser: "ຜູ້ໃຊ້ໃໝ່",
      noPhone: "ບໍ່ມີເບີໂທ",
      settings: "ຕັ້ງຄ່າ",
      language: "ພາສາ",
      languageDesc: "ປ່ຽນພາສາທົ່ວທັງແອັບ",
      account: "ບັນຊີຜູ້ໃຊ້",
      personalInfo: "ຂໍ້ມູນສ່ວນຕົວ",
      personalInfoDesc: "ຈັດການຊື່, ເບີໂທ, ອີເມວຂອງທ່ານ",
      address: "ທີ່ຢູ່ຮັບບໍລິການ",
      addressEmpty: "ຍັງບໍ່ໄດ້ໃສ່ທີ່ຢູ່",
      security: "ຄວາມປອດໄພ",
      securityDesc: "ຢືນຢັນຕົວຕົນຜ່ານເບີໂທລະສັບ",
      securitySoon: "ຄຸນສົມບັດນີ້ຍັງບໍ່ພ້ອມໃຊ້ງານ, ຈະເປີດໃຫ້ໃຊ້ໃນອະນາຄົດ",
      history: "ປະຫວັດ",
      historyItem: "ປະຫວັດການໃຊ້ບໍລິການ",
      historyItemDesc: "ເບິ່ງລາຍການທີ່ຜ່ານມາ",
      logout: "ອອກຈາກລະບົບ",
      editPersonalTitle: "ແກ້ໄຂຂໍ້ມູນສ່ວນຕົວ",
      editAddressTitle: "ແກ້ໄຂທີ່ຢູ່ຮັບບໍລິການ",
      name: "ຊື່",
      phone: "ເບີໂທລະສັບ",
      email: "ອີເມວ",
      cancel: "ຍົກເລີກ",
      save: "ບັນທຶກ",
      saving: "ກຳລັງບັນທຶກ...",
    },
    chooseRole: {
      title: "ທ່ານແມ່ນໃຜ?",
      subtitle: "ເລືອກປະເພດບັນຊີເພື່ອລົງທະບຽນ",
      customerTitle: "ລົງທະບຽນເປັນຜູ້ໃຊ້",
      customerDesc: "ຄົ້ນຫາ ແລະ ຈ້າງຊ່າງໃກ້ບ້ານທ່ານ",
      techTitle: "ລົງທະບຽນເປັນຊ່າງ",
      techDesc: "ຮັບວຽກ ແລະ ຫາລູກຄ້າໃໝ່",
      back: "← ກັບຄືນ",
    },
    login: {
      brand: "ຊ່າງດ່ວນ",
      welcomeBack: "Welcome back! ໃສ່ເບີໂທເພື່ອເຂົ້າສູ່ລະບົບ",
      enterOtpSent: (phone: string) => `ໃສ່ລະຫັດ OTP ທີ່ສົ່ງໄປຫາ ${phone}`,
      phoneLabel: "ເບີໂທລະສັບ",
      phonePlaceholder: "020xxxxxxxx",
      phoneInvalid: "ກະລຸນາໃສ່ເບີໂທໃຫ້ຖືກຕ້ອງ",
      sendFailed: "ສົ່ງລະຫັດບໍ່ສຳເລັດ",
      sendOtp: "ສົ່ງລະຫັດ OTP",
      sending: "ກຳລັງສົ່ງລະຫັດ...",
      devModeLabel: "(ໂໝດທົດສອບ) ລະຫັດ OTP:",
      otpLabel: "ລະຫັດ OTP (6 ຫຼັກ)",
      otpIncomplete: "ກະລຸນາໃສ່ລະຫັດ OTP ໃຫ້ຄົບ 6 ຫຼັກ",
      otpInvalid: "ລະຫັດ OTP ບໍ່ຖືກຕ້ອງ ຫຼື ໝົດອາຍຸແລ້ວ",
      noAccountFound: "ບໍ່ພົບບັນຊີນີ້ໃນລະບົບ, ກະລຸນາລົງທະບຽນກ່ອນ",
      changePhone: "← ປ່ຽນເບີໂທ",
      resend: (s: number) => `ສົ່ງລະຫັດຄືນໃໝ່ (${s}s)`,
      resendNow: "ສົ່ງລະຫັດຄືນໃໝ່",
      verify: "ຢືນຢັນ ແລະ ເຂົ້າສູ່ລະບົບ",
      verifying: "ກຳລັງກວດສອບ...",
      orSignInWith: "Or sign in with",
      noAccount: "Don't have an account?",
      signUp: "Sign Up",
    },
    register: {
      brand: "ຊ່າງດ່ວນ",
      createTitle: "ສ້າງບັນຊີໃໝ່ ດ້ວຍເບີໂທຂອງທ່ານ",
      enterOtpSent: (phone: string) => `ໃສ່ລະຫັດ OTP ທີ່ສົ່ງໄປຫາ ${phone}`,
      nameLabel: "ຊື່",
      namePlaceholder: "ໃສ່ຊື່ຂອງທ່ານ",
      nameRequired: "ກະລຸນາໃສ່ຊື່",
      phoneLabel: "ເບີໂທລະສັບ",
      phonePlaceholder: "020xxxxxxxx",
      phoneInvalid: "ກະລຸນາໃສ່ເບີໂທໃຫ້ຖືກຕ້ອງ",
      sendOtp: "ສົ່ງລະຫັດ OTP",
      sending: "ກຳລັງສົ່ງລະຫັດ...",
      devModeLabel: "(ໂໝດທົດສອບ) ລະຫັດ OTP:",
      otpLabel: "ລະຫັດ OTP (6 ຫຼັກ)",
      otpIncomplete: "ກະລຸນາໃສ່ລະຫັດ OTP ໃຫ້ຄົບ 6 ຫຼັກ",
      otpInvalid: "ລະຫັດ OTP ບໍ່ຖືກຕ້ອງ ຫຼື ໝົດອາຍຸແລ້ວ",
      editInfo: "← ແກ້ໄຂຂໍ້ມູນ",
      resend: (s: number) => `ສົ່ງລະຫັດຄືນໃໝ່ (${s}s)`,
      resendNow: "ສົ່ງລະຫັດຄືນໃໝ່",
      verify: "ຢືນຢັນ ແລະ ສ້າງບັນຊີ",
      verifying: "ກຳລັງກວດສອບ...",
      alreadyHave: "ມີບັນຊີແລ້ວບໍ່?",
      loginLink: "ເຂົ້າສູ່ລະບົບ",
    },
  },
  th: {
    welcome: {
      skip: "ข้าม",
      titleLine1: "ยินดีต้อนรับสู่",
      titleAccent: "ช่างด่วน",
      subtitle: "ค้นหาช่างใกล้บ้านคุณได้อย่างรวดเร็ว ปลอดภัย และเชื่อถือได้",
      start: "เริ่มต้น",
      checking: "กำลังตรวจสอบ...",
    },
    nav: {
      home: "หน้าหลัก",
      bookings: "แชท",
      history: "ประวัติ",
      profile: "โปรไฟล์",
    },
    chooseRole: {
      title: "คุณคือใคร?",
      subtitle: "เลือกประเภทบัญชีเพื่อลงทะเบียน",
      customerTitle: "ลงทะเบียนเป็นผู้ใช้",
      customerDesc: "ค้นหาและจ้างช่างใกล้บ้านคุณ",
      techTitle: "ลงทะเบียนเป็นช่าง",
      techDesc: "รับงานและหาลูกค้าใหม่",
      back: "← กลับ",
    },
    login: {
      brand: "ช่างด่วน",
      welcomeBack: "ยินดีต้อนรับกลับ! ใส่เบอร์โทรเพื่อเข้าสู่ระบบ",
      enterOtpSent: (phone: string) => `ใส่รหัส OTP ที่ส่งไปยัง ${phone}`,
      phoneLabel: "เบอร์โทรศัพท์",
      phonePlaceholder: "020xxxxxxxx",
      phoneInvalid: "กรุณาใส่เบอร์โทรให้ถูกต้อง",
      sendFailed: "ส่งรหัสไม่สำเร็จ",
      sendOtp: "ส่งรหัส OTP",
      sending: "กำลังส่งรหัส...",
      devModeLabel: "(โหมดทดสอบ) รหัส OTP:",
      otpLabel: "รหัส OTP (6 หลัก)",
      otpIncomplete: "กรุณาใส่รหัส OTP ให้ครบ 6 หลัก",
      otpInvalid: "รหัส OTP ไม่ถูกต้อง หรือหมดอายุแล้ว",
      noAccountFound: "ไม่พบบัญชีนี้ในระบบ กรุณาลงทะเบียนก่อน",
      changePhone: "← เปลี่ยนเบอร์โทร",
      resend: (s: number) => `ส่งรหัสอีกครั้ง (${s}s)`,
      resendNow: "ส่งรหัสอีกครั้ง",
      verify: "ยืนยันและเข้าสู่ระบบ",
      verifying: "กำลังตรวจสอบ...",
      orSignInWith: "หรือเข้าสู่ระบบด้วย",
      noAccount: "ยังไม่มีบัญชี?",
      signUp: "สมัครสมาชิก",
    },
    register: {
      brand: "ช่างด่วน",
      createTitle: "สร้างบัญชีใหม่ด้วยเบอร์โทรของคุณ",
      enterOtpSent: (phone: string) => `ใส่รหัส OTP ที่ส่งไปยัง ${phone}`,
      nameLabel: "ชื่อ",
      namePlaceholder: "ใส่ชื่อของคุณ",
      nameRequired: "กรุณาใส่ชื่อ",
      phoneLabel: "เบอร์โทรศัพท์",
      phonePlaceholder: "020xxxxxxxx",
      phoneInvalid: "กรุณาใส่เบอร์โทรให้ถูกต้อง",
      sendOtp: "ส่งรหัส OTP",
      sending: "กำลังส่งรหัส...",
      devModeLabel: "(โหมดทดสอบ) รหัส OTP:",
      otpLabel: "รหัส OTP (6 หลัก)",
      otpIncomplete: "กรุณาใส่รหัส OTP ให้ครบ 6 หลัก",
      otpInvalid: "รหัส OTP ไม่ถูกต้อง หรือหมดอายุแล้ว",
      editInfo: "← แก้ไขข้อมูล",
      resend: (s: number) => `ส่งรหัสอีกครั้ง (${s}s)`,
      resendNow: "ส่งรหัสอีกครั้ง",
      verify: "ยืนยันและสร้างบัญชี",
      verifying: "กำลังตรวจสอบ...",
      alreadyHave: "มีบัญชีแล้ว?",
      loginLink: "เข้าสู่ระบบ",
    },
    home: {
      title: "ช่างด่วน",
      searchPlaceholder: "ค้นหาชื่อ หรือ พื้นที่...",
      location: "นครหลวงเวียงจันทน์",
      greet: (name: string) => `สวัสดี, ${name}`,
      banner: {
        badge: "บริการปลอดภัย",
        title: "บริการช่างด่วน",
        desc: "ช่างเข้าบ้านคุณ รวดเร็ว ไว้ใจได้ พร้อมส่วนลดพิเศษ",
        discount: "ส่วนลด: 10%",
      },
      perksTitle: "สิทธิพิเศษสำหรับคุณ",
      perk1Title: "ส่วนลด 10%",
      perk1Desc: "บริการช่างไฟฟ้าครั้งแรก",
      perk2Title: "ส่วนลด 5%",
      perk2Desc: "บริการทุกประเภทวันแรก",
      categoriesTitle: "หมวดหมู่บริการ",
      featuredTitle: "บริการแนะนำ",
      categories: {
        electric: "ช่างไฟฟ้า",
        plumbing: "ช่างประปา",
        beauty: "ช่างเสริมสวย",
        carRepair: "ช่างซ่อมรถ",
        phoneRepair: "ช่างซ่อมโทรศัพท์",
        airRepair: "ช่างแอร์"
      },
    },
    history: {
      title: "ประวัติการใช้บริการ",
      empty: "ยังไม่มีประวัติ",
      emptyDesc: "ประวัติการใช้บริการของคุณจะแสดงที่นี่",
      done: "สำเร็จ",
      cancelled: "ยกเลิก",
    },
    bookings: {
      title: "แชท",
      loading: "กำลังโหลด...",
      empty: "ยังไม่มีการแชท",
      emptyDesc: "เริ่มแชทหาช่างที่หน้าหลักได้เลย",
      startConvo: "เริ่มการสนทนา...",
      unread: "ยังไม่อ่าน",
    },
    technicianHome: {
      chatListTitle: (name: string) => `รายการแชท (${name})`,
      profileTitle: "ข้อมูลช่าง",
      loading: "กำลังโหลด...",
      noTech: "ไม่พบข้อมูลช่าง",
      noChats: "ยังไม่มีลูกค้าแชทเข้ามา",
      tabChat: "แชทลูกค้า",
      tabProfile: "ข้อมูลช่าง",
      logoutTitle: "ออกจากระบบ",
      logoutConfirm: "คุณแน่ใจหรือไม่ว่าจะออกจากระบบ?",
      cancel: "ยกเลิก",
      logout: "ออกจากระบบ",
      unread: "ยังไม่อ่าน",
    },
    profile: {
      appTitle: "ช่างด่วน",
      loading: "กำลังโหลด...",
      newUser: "ผู้ใช้ใหม่",
      noPhone: "ไม่มีเบอร์โทร",
      settings: "ตั้งค่า",
      language: "ภาษา",
      languageDesc: "เปลี่ยนภาษาทั่วทั้งแอป",
      account: "บัญชีผู้ใช้",
      personalInfo: "ข้อมูลส่วนตัว",
      personalInfoDesc: "จัดการชื่อ, เบอร์โทร, อีเมลของคุณ",
      address: "ที่อยู่รับบริการ",
      addressEmpty: "ยังไม่ได้ใส่ที่อยู่",
      security: "ความปลอดภัย",
      securityDesc: "ยืนยันตัวตนผ่านเบอร์โทรศัพท์",
      securitySoon: "คุณสมบัตินี้ยังไม่พร้อมใช้งาน จะเปิดให้ใช้ในอนาคต",
      history: "ประวัติ",
      historyItem: "ประวัติการใช้บริการ",
      historyItemDesc: "ดูรายการที่ผ่านมา",
      logout: "ออกจากระบบ",
      editPersonalTitle: "แก้ไขข้อมูลส่วนตัว",
      editAddressTitle: "แก้ไขที่อยู่รับบริการ",
      name: "ชื่อ",
      phone: "เบอร์โทรศัพท์",
      email: "อีเมล",
      cancel: "ยกเลิก",
      save: "บันทึก",
      saving: "กำลังบันทึก...",
    },
  },
  en: {
    welcome: {
      skip: "Skip",
      titleLine1: "Welcome to",
      titleAccent: "Chang Duan",
      subtitle: "Find trusted technicians near you — fast and safe.",
      start: "Get Started",
      checking: "Checking...",
    },
    nav: {
      home: "Home",
      bookings: "Chats",
      history: "History",
      profile: "Profile",
    },
    chooseRole: {
      title: "Who are you?",
      subtitle: "Choose an account type to register",
      customerTitle: "Register as a Customer",
      customerDesc: "Find and hire technicians near you",
      techTitle: "Register as a Technician",
      techDesc: "Get jobs and find new customers",
      back: "← Back",
    },
    login: {
      brand: "Chang Duan",
      welcomeBack: "Welcome back! Enter your phone number to log in",
      enterOtpSent: (phone: string) => `Enter the OTP sent to ${phone}`,
      phoneLabel: "Phone Number",
      phonePlaceholder: "020xxxxxxxx",
      phoneInvalid: "Please enter a valid phone number",
      sendFailed: "Failed to send code",
      sendOtp: "Send OTP",
      sending: "Sending code...",
      devModeLabel: "(Test mode) OTP code:",
      otpLabel: "OTP Code (6 digits)",
      otpIncomplete: "Please enter the full 6-digit OTP",
      otpInvalid: "Invalid or expired OTP",
      noAccountFound: "No account found. Please register first",
      changePhone: "← Change phone number",
      resend: (s: number) => `Resend code (${s}s)`,
      resendNow: "Resend code",
      verify: "Verify & Log In",
      verifying: "Verifying...",
      orSignInWith: "Or sign in with",
      noAccount: "Don't have an account?",
      signUp: "Sign Up",
    },
    register: {
      brand: "Chang Duan",
      createTitle: "Create a new account with your phone number",
      enterOtpSent: (phone: string) => `Enter the OTP sent to ${phone}`,
      nameLabel: "Name",
      namePlaceholder: "Enter your name",
      nameRequired: "Please enter your name",
      phoneLabel: "Phone Number",
      phonePlaceholder: "020xxxxxxxx",
      phoneInvalid: "Please enter a valid phone number",
      sendOtp: "Send OTP",
      sending: "Sending code...",
      devModeLabel: "(Test mode) OTP code:",
      otpLabel: "OTP Code (6 digits)",
      otpIncomplete: "Please enter the full 6-digit OTP",
      otpInvalid: "Invalid or expired OTP",
      editInfo: "← Edit info",
      resend: (s: number) => `Resend code (${s}s)`,
      resendNow: "Resend code",
      verify: "Verify & Create Account",
      verifying: "Verifying...",
      alreadyHave: "Already have an account?",
      loginLink: "Log In",
    },
    home: {
      title: "Chang Duan",
      searchPlaceholder: "Search name or area...",
      location: "Vientiane Capital",
      greet: (name: string) => `Hello, ${name}`,
      banner: {
        badge: "Safe Service",
        title: "Express Technician Service",
        desc: "Technicians at your home, fast and trustworthy, with special discounts",
        discount: "Discount: 10%",
      },
      perksTitle: "Perks For You",
      perk1Title: "10% Off",
      perk1Desc: "First-time electrician service",
      perk2Title: "5% Off",
      perk2Desc: "Any service, first day",
      categoriesTitle: "Service Categories",
      featuredTitle: "Featured Services",
      categories: {
        electric: "Electrician",
        plumbing: "Plumber",
        beauty: "Beautician",
        carRepair: "Car Repair",
        phoneRepair: "Phone Repair",
        airReppair : "air Repair",
      },
    },
    history: {
      title: "Service History",
      empty: "No history yet",
      emptyDesc: "Your service history will show up here",
      done: "Done",
      cancelled: "Cancelled",
    },
    bookings: {
      title: "Chats",
      loading: "Loading...",
      empty: "No chats yet",
      emptyDesc: "Start chatting with a technician from the home page",
      startConvo: "Start the conversation...",
      unread: "Unread",
    },
    technicianHome: {
      chatListTitle: (name: string) => `Chats (${name})`,
      profileTitle: "Technician Info",
      loading: "Loading...",
      noTech: "Technician not found",
      noChats: "No customers have messaged yet",
      tabChat: "Customer Chats",
      tabProfile: "Technician Info",
      logoutTitle: "Log Out",
      logoutConfirm: "Are you sure you want to log out?",
      cancel: "Cancel",
      logout: "Log Out",
      unread: "Unread",
    },
    profile: {
      appTitle: "Chang Duan",
      loading: "Loading...",
      newUser: "New User",
      noPhone: "No phone number",
      settings: "Settings",
      language: "Language",
      languageDesc: "Change the app language",
      account: "Account",
      personalInfo: "Personal Info",
      personalInfoDesc: "Manage your name, phone, and email",
      address: "Service Address",
      addressEmpty: "No address set yet",
      security: "Security",
      securityDesc: "Verify identity via phone number",
      securitySoon: "This feature is not available yet, coming soon",
      history: "History",
      historyItem: "Service History",
      historyItemDesc: "View past services",
      logout: "Log Out",
      editPersonalTitle: "Edit Personal Info",
      editAddressTitle: "Edit Service Address",
      name: "Name",
      phone: "Phone Number",
      email: "Email",
      cancel: "Cancel",
      save: "Save",
      saving: "Saving...",
    },
  },
};

interface LanguageContextType {
  lang: LangKey;
  setLang: (lang: LangKey) => void;
  t: (typeof translations)["lo"];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangKey>(
    () => (localStorage.getItem(LANG_STORAGE_KEY) as LangKey) || "lo"
  );

  const setLang = (l: LangKey) => {
    setLangState(l);
    localStorage.setItem(LANG_STORAGE_KEY, l);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage ຕ້ອງໃຊ້ພາຍໃນ LanguageProvider");
  }
  return context;
}